### ISSUE TITLE
Option to turn off PCP

### ISSUE THREAD

**Issue by martinpitt** [martinpitt/performance-graphs#18]
This page will replace the "enable pcp" button on Overview. The empty state provides the "on", but there is no "off" button.

**Comment by garrett** [comment]
This isn't accurate — disregard the content, the style, etc. Focus on the configuration box.

Perhaps we could have a settings section like this? Where it's shoved under the shortest card on the right.

![metrics-config](https://user-images.githubusercontent.com/10246/92609170-90786380-f2b6-11ea-99f7-579c9dd1311b.png)

Since the toggle is probably too visible and too easy to turn off, we could have something like the CPU mitigations @ https://localhost:9090/system/hwinfo — where there's a settings link that brings up a dialog with a toggle and a confirmation button. (This would only be for disabling, as it would presumably disable the service _and_ remove packages.)

**Comment by marusak** [comment]
Moved to https://github.com/cockpit-project/cockpit/issues/14803

**Comment by garrett** [comment]
BTW, there's a "transfer issue" link on the bottom of the right-side column that lets you move issues from one repo to another, without having to open and close the issue.

**Comment by martinpitt** [comment]
@garrett: This only works within one organization; it's not possible to transfer from martinpitt/foo to cockpit-project/bar.

**Comment by garrett** [comment]
@martinpitt: Oh, right! That seems like a rather large oversight on GitHub's part, but that makes sense as to why we didn't use it here.
