### ISSUE TITLE
Link current disk mount points to Storage page

### ISSUE THREAD

**Issue by martinpitt** [martinpitt/performance-graphs#43]

**Comment by martinpitt** [comment]
That's not actually that trivial, as mount points don't correspond 1:1 to the storage page. Let's defer this a bit.

**Comment by martinpitt** [comment]
Plan:
 * If we have cockpit-storage manifest, use udisks and turn the names into links to the storage page.
 * If we don't, then keep the current approach.

**Comment by martinpitt** [comment]
The Storage page does not actually have by-filesystem paths, it's organized by device, not mounts. E.g. /home lives on path `/storage#/vg/fedora` on my system. That mapping is not canonical, but specific to internal details of the storage page. So once again, this is annoyingly hard, and we could perhaps just add a link to the storage page into the title.

**Comment by martinpitt** [comment]
@garrett: How about like this?

Current master:

![disks-master](https://user-images.githubusercontent.com/200109/94412547-33b3ee80-017a-11eb-9513-e199bb064ad0.png)

Now:
![disks-pr](https://user-images.githubusercontent.com/200109/94412550-357db200-017a-11eb-97bb-08a31f62fab8.png)

It's a bit strange to attach the tooltip to the mount point instead of the free space, but the former is now a link (and thus focusable), while the latter is not. The links go to the main storage page, which has a "Filesystems" card which mentions them all. There is no more specific subpage.

**Comment by garrett** [comment]
It'd be better if the tooltip would show up on the hovering the whole progress area, including the free text and the progress bar. It would also be better if the tooltip would be anchored to the whole thing instead of just the link.

But I'm fine with this going in now and fixing that up later, as long as we keep it in mind and get it done eventually.

(So push and merge the PR that does this and keep the issue open or open up another issue to handle it fully.)

**Comment by martinpitt** [comment]
@garrett: hah, I think I got it:

![disks-tooltip-progress](https://user-images.githubusercontent.com/200109/94418141-43830100-0181-11eb-9ad2-fd1fc1d0bd05.png)

This can be tabbed through or hovered on, and the entire progress including title acts as a link now.
